name: Export ipa
on: 
  workflow_dispatch:
jobs:
  deploy:
    name: Export ipa file
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Archiving project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/archive_app.sh
      - name: Exporting .ipa
        run: ./.github/scripts/export_ipa.sh
      - name: upload to PGY
        env:
          PGY_API_KEY: ${{ secrets.PGY_API_KEY }}
        run: ./.github/scripts/upload_pgy.sh
