name: PGY
on: 
  workflow_dispatch:
jobs:
  deploy:
    name: Deploying to PGY
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/secrets/decrypt_secrets.sh
      - name: Install dependency
        run: ./.github/scripts/processDependency.sh
      - name: Archiving project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/archive_app.sh
      - name: Exporting .ipa
        run: ./.github/scripts/export_ipa.sh
      - name: upload to PGY
        env:
          PGY_API_KEY: ${{ secrets.PGY_API_KEY }}
        run: ./.github/scripts/upload_pgy.sh
